name: RunChecks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Install dependencies
      run: |
        sudo apt-get -y install python3-apt
        python -m pip install --upgrade pip
        pip install flask flask_httpauth pip_api pylint jsonschema
    - name: Analysing the code with pylint
      run: |
        pylint -dR1722,R0914,R0912,R0915,R0401,R0801,E0401,E0402,C0206 apt2sbom/*.py
    - name: Attempting install
      run: |
        pip install .
    - name: Try running
      run: |
        apt2sbom -c > cy.json
        python tests/validate.py tests/cyclonedx-schema.json cy.json
        apt2sbom -y > /dev/null
        apt2sbom -j > spdx.json
        python tests/validate.py tests/spdx-schema.json spdx.json
